export const categories = [
  'Electronics',
  'Clothing',
  'Home & Garden',
  'Books',
  'Toys',
  'Sports',
  'Beauty',
  'Health',
  'Automotive',
  'Jewelry',
  'Food & Beverages',
  'Pet Supplies',
  'Office',
  'Arts & Crafts',
  'Music',
  'Movies',
  'Games',
  'Baby',
  'Tools',
  'Outdoors',
  'Industrial',
  'Fashion Accessories',
  'Furniture',
  'Appliances',
];
